apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: grocery-automate
  labels:
    app.kubernetes.io/name: grocery-automate
    app.kubernetes.io/component: catalog-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grocery-automate
    app.kubernetes.io/component: catalog-service
  ports:
    - name: http
      port: 8080
      targetPort: http
